Registry functions: add :date
tc39/proposal-intl-messageformat pull request #51
Opened 2024-04-23 13:14 UTC by ryzokuken

Fix an error with `:dateTime`
Refactor parts of `:dateTime`
Add `:date`

2024-04-23 14:53 UTC, eemeli requested changes

2024-04-23 14:53 UTC, eemeli commented on spec.emu
> +          1. let value
?

2024-04-23 14:53 UTC, eemeli commented on spec.emu
> +              1. Perform ? Call(Object.assign, *undefined*, « _opts_, _inputOptions_ »).
Option resolution should happen after value resolution, as it could fail and it has external visibility.

2024-04-23 14:53 UTC, eemeli commented on spec.emu
> +            1. If InstanceOfOperator(_input_, %Date%) is *false* and IsCallable(_valueOf_) is *true*, set _input_ to Call(_valueOf_, _input_).
For instances of Date, we should not try to Get "valueOf".

2024-04-23 14:53 UTC, eemeli commented on spec.emu
> +          1. Else if Type(_input_) is Object, let _value_ be _input_.
If the previous steps were to work on _value_ and not _input_, this line would be unnecessary.

2024-04-23 14:53 UTC, eemeli commented on spec.emu
> +        1. Let _dateTime_ be CreateBuiltinFunction(_dateTimeSteps_, *3*, *"dateTime"*, « »).
```suggestion
        1. Let _dateTime_ be CreateBuiltinFunction(_dateTimeSteps_, *3*, *"datetime"*, « »).
```

2024-04-23 14:53 UTC, eemeli commented on spec.emu
> +              1. Perform ? Set(_opts_, _optName_, _optValue_, *"true"*).
This is wrong; the only [supported option](https://github.com/unicode-org/message-format-wg/blob/main/spec/registry.md#the-date-function) for `:date` is `style`.
```suggestion
          1. If _dateStyle_ is *null* or *undefined*, then
            1. Set _dateStyle_ to *"short"*.
```

2024-04-23 17:23 UTC, ryzokuken commented on spec.emu
> +          1. let value
Sorry for leaving that in

2024-04-23 18:23 UTC, eemeli commented on spec.emu
> +              1. Perform ? Set(_opts_, _optName_, _optValue_, *"true"*).
Ah, good point. But note that that code is not working on the `options` that are set by the expression options, but the `opt` which has had the `input.options` applied to it.

So while it's not allowing for any other expression options than `style`, it is supporting "locale options" when they're set on the operand's resolved value. This allows for e.g. this:

```js
const msg = 'Today is {$date :date style=long}'
const mf = new Intl.MessageFormat(msg, 'en')

const date = new Date()
mf.format({ date }) // 'Today is April 23, 2024'

date.options = { calendar: 'persian' }
mf.format({ date }) // 'Today is Ordibehesht 4, 1403 AP'
```

2024-04-24 20:51 UTC, ryzokuken commented
@eemeli PTAL now. Regarding the first set of changes, I didn't entirely understand your comments (I think? I could be positively surprised) but I made some improvements that might address your concern.

In the second set of changes, your comment made me realize that I was misreading the code? Sorry for that, the updated spec should make a lot more sense.

2024-04-24 21:06 UTC, eemeli requested changes

2024-04-24 21:21 UTC, ryzokuken commented on spec.emu
> +              1. If IsCallable(_valueOf_) is *true*, set _input_ to Call(_valueOf_, _input_).
I see, so basically if input is a non-date object, we're looking for `input.valueOf().options` and not `input.options`?

2024-04-25 05:36 UTC, eemeli commented on spec.emu
> +              1. If IsCallable(_valueOf_) is *true*, set _input_ to Call(_valueOf_, _input_).
No, still `input.options`. Note that I used _input_ and _value_ differently above than in your spec text. Looking at it now again, the corresponding `:number` code might also have some timing issues.

2024-04-25 16:06 UTC, ryzokuken commented on spec.emu
> +              1. If IsCallable(_valueOf_) is *true*, set _input_ to Call(_valueOf_, _input_).
I made an update, feel free to check them out whenever you can. In the meantime I'll check what `:numbers` does too. JFYI btw, now we've diverged from what the polyfill does (not that the spec needs to follow the polyfill, but just wanted to point that out): https://github.com/messageformat/messageformat/blob/main/packages/mf2-messageformat/src/functions/datetime.ts#L126-L146

2024-04-26 06:07 UTC, eemeli commented on spec.emu
> +              1. If IsCallable(_valueOf_) is *true*, set _input_ to Call(_valueOf_, _input_).
Very happy to update the polyfill to match the spec for a change, rather than vice versa

2024-04-26 06:31 UTC, eemeli approved these changes
Looks good, if we include the one refactor proposed inline.

2024-04-26 11:18 UTC, ryzokuken commented
Overall looks good to me, although I still feel like we could avoid repeating the `if (input.options) {...}` part while keeping the rest as-is.

2024-04-30 11:08 UTC, ryzokuken commented
@eemeli this might look better now :D

2024-04-30 11:14 UTC, eemeli approved these changes
Yup, looks good!

2024-04-30 11:15 UTC, merged